AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for our CICD PR'

Parameters: 
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production
  RandomNumber:
    Type: Number
    Default: 12345 

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-${AWS::Region}-${AWS::AccountId}-${RandomNumber}-bucket' # dynamic name
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionsTesting

Outputs:
  BucketName:
    Description: 'Name of created S3 Bucket'
    Value: !Ref MyS3Bucket
