name: Validate CloudFormation on PR

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths:
      - 'cloudformation/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/s3-bucket.yml

      - name: Deploy our stack
        run: |
          stack_name="pr-test-stack-${{ github.event.pull_request.number }}"
          aws cloudformation create-stack \
            --stack-name $stack_name \
            --template-body file://cloudformation/s3-bucket.yml \
            --parameters ParameterKey=Environment,ParameterValue=test
        